---
- !ruby/object:Producto
  nombre: Cruzcampo 1/3
  tipo: cerveza
  precision: 2
  minimo: 1.1
  maximo: 1.7
  precio_actual: 1.64
  precio_anterior: 1.28
- !ruby/object:Producto
  nombre: Heineken 1/3
  tipo: cerveza
  precision: 2
  minimo: 1.1
  maximo: 1.7
  precio_actual: 1.68
  precio_anterior: 1.34
- !ruby/object:Producto
  nombre: Heineken 0,0 1/3
  tipo: cerveza
  precision: 2
  minimo: 1.2
  maximo: 1.8
  precio_actual: 1.28
  precio_anterior: 1.22
- !ruby/object:Producto
  nombre: Amstel 1/3
  tipo: cerveza
  precision: 2
  minimo: 1.1
  maximo: 1.7
  precio_actual: 1.44
  precio_anterior: 1.18
- !ruby/object:Producto
  nombre: Cruzcampo 1/5
  tipo: cerveza
  precision: 2
  minimo: 0.7
  maximo: 1.2
  precio_actual: 1.1
  precio_anterior: 0.82
- !ruby/object:Producto
  nombre: Jarra
  tipo: cerveza
  precision: 2
  minimo: 1.5
  maximo: 2.2
  precio_actual: 1.99
  precio_anterior: 2.01
- !ruby/object:Producto
  nombre: Tubo
  tipo: cerveza
  precision: 2
  minimo: 0.9
  maximo: 1.5
  precio_actual: 1.45
  precio_anterior: 1.02
- !ruby/object:Producto
  nombre: Ca침a
  tipo: cerveza
  precision: 2
  minimo: 0.7
  maximo: 1.1
  precio_actual: 0.83
  precio_anterior: 1.03
- !ruby/object:Producto
  nombre: Tinto casero vaso ancho
  tipo: tinto
  precision: 2
  minimo: 1.2
  maximo: 1.7
  precio_actual: 1.26
  precio_anterior: 1.31
- !ruby/object:Producto
  nombre: Tinto casero tubo
  tipo: tinto
  precision: 2
  minimo: 0.9
  maximo: 1.3
  precio_actual: 1.2
  precio_anterior: 1.12
- !ruby/object:Producto
  nombre: Rioja
  tipo: tinto
  precision: 2
  minimo: 1.1
  maximo: 1.8
  precio_actual: 1.6
  precio_anterior: 1.72
- !ruby/object:Producto
  nombre: Espumoso
  tipo: tinto
  precision: 2
  minimo: 1.2
  maximo: 1.8
  precio_actual: 1.39
  precio_anterior: 1.75
- !ruby/object:Producto
  nombre: Rueda
  tipo: tinto
  precision: 2
  minimo: 1.2
  maximo: 1.8
  precio_actual: 1.78
  precio_anterior: 1.52
- !ruby/object:Producto
  nombre: Mcnolo
  tipo: racion
  precision: 2
  minimo: 3.5
  maximo: 4.1
  precio_actual: 4.01
  precio_anterior: 4.01
- !ruby/object:Producto
  nombre: Tender
  tipo: racion
  precision: 2
  minimo: 5.2
  maximo: 6
  precio_actual: 5.81
  precio_anterior: 5.64
- !ruby/object:Producto
  nombre: L치grimas
  tipo: racion
  precision: 2
  minimo: 5
  maximo: 5.8
  precio_actual: 5.37
  precio_anterior: 5.7
- !ruby/object:Producto
  nombre: Tex y kebab
  tipo: racion
  precision: 2
  minimo: 3.5
  maximo: 4.1
  precio_actual: 3.55
  precio_anterior: 4.06
- !ruby/object:Producto
  nombre: Montadito
  tipo: racion
  precision: 2
  minimo: 1.1
  maximo: 1.6
  precio_actual: 1.6
  precio_anterior: 1.5
- !ruby/object:Producto
  nombre: Croquetas
  tipo: racion
  precision: 2
  minimo: 5
  maximo: 5.7
  precio_actual: 5.31
  precio_anterior: 5.41
- !ruby/object:Producto
  nombre: Alitas
  tipo: racion
  precision: 2
  minimo: 5
  maximo: 5.7
  precio_actual: 5.56
  precio_anterior: 5.65
- !ruby/object:Producto
  nombre: Flamenquines
  tipo: racion
  precision: 2
  minimo: 3.8
  maximo: 4.2
  precio_actual: 4.09
  precio_anterior: 3.93
- !ruby/object:Producto
  nombre: Bravas
  tipo: racion
  precision: 2
  minimo: 3.3
  maximo: 3.7
  precio_actual: 3.46
  precio_anterior: 3.37
- !ruby/object:Producto
  nombre: Larios 12
  tipo: ginebra
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 2.82
  precio_anterior: 2.57
- !ruby/object:Producto
  nombre: Larios
  tipo: ginebra
  precision: 2
  minimo: 2.2
  maximo: 2.8
  precio_actual: 2.53
  precio_anterior: 2.72
- !ruby/object:Producto
  nombre: Beefeater
  tipo: ginebra
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 3.03
  precio_anterior: 2.92
- !ruby/object:Producto
  nombre: Puerto de Indias
  tipo: ginebra
  precision: 2
  minimo: 2.9
  maximo: 3.6
  precio_actual: 3.18
  precio_anterior: 3.11
- !ruby/object:Producto
  nombre: Barcel칩
  tipo: ron
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 2.7
  precio_anterior: 3.11
- !ruby/object:Producto
  nombre: Brugal
  tipo: ron
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 2.67
  precio_anterior: 2.77
- !ruby/object:Producto
  nombre: Areucas
  tipo: ron
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 2.67
  precio_anterior: 3.25
- !ruby/object:Producto
  nombre: Cacique
  tipo: ron
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 2.54
  precio_anterior: 2.91
- !ruby/object:Producto
  nombre: Ron Miel
  tipo: ron
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 3.15
  precio_anterior: 3.04
- !ruby/object:Producto
  nombre: Negrita
  tipo: ron
  precision: 2
  minimo: 2.2
  maximo: 2.8
  precio_actual: 2.67
  precio_anterior: 2.48
- !ruby/object:Producto
  nombre: JB
  tipo: whisky
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 3.03
  precio_anterior: 3.21
- !ruby/object:Producto
  nombre: DYC 8
  tipo: whisky
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 3.28
  precio_anterior: 2.97
- !ruby/object:Producto
  nombre: Ballantine
  tipo: whisky
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 3.05
  precio_anterior: 2.99
- !ruby/object:Producto
  nombre: White Label
  tipo: whisky
  precision: 2
  minimo: 2.5
  maximo: 3.3
  precio_actual: 2.68
  precio_anterior: 3.17
- !ruby/object:Producto
  nombre: Doble V
  tipo: whisky
  precision: 2
  minimo: 2.2
  maximo: 2.8
  precio_actual: 2.33
  precio_anterior: 2.49
- !ruby/object:Producto
  nombre: Pi침a colada
  tipo: cocktail
  precision: 2
  minimo: 2.9
  maximo: 3.8
  precio_actual: 3.68
  precio_anterior: 3.31
- !ruby/object:Producto
  nombre: Daikiri
  tipo: cocktail
  precision: 2
  minimo: 2.9
  maximo: 3.8
  precio_actual: 3.33
  precio_anterior: 3.45
- !ruby/object:Producto
  nombre: Mojito
  tipo: cocktail
  precision: 2
  minimo: 2.9
  maximo: 3.8
  precio_actual: 3.08
  precio_anterior: 3.27
- !ruby/object:Producto
  nombre: En tubo
  tipo: chismaillo
  precision: 2
  minimo: 2.0
  maximo: 2.4
  precio_actual: 2.34
  precio_anterior: 2.37
- !ruby/object:Producto
  nombre: En vaso ancho
  tipo: chismaillo
  precision: 2
  minimo: 2.3
  maximo: 2.8
  precio_actual: 2.58
  precio_anterior: 2.34
